version: '3.4'

services:

  zammad-backup:
    container_name: zammad-backup
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    links:
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/backup:/var/tmp/zammad
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.2
        aliases:
          - zammad-backup
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-elasticsearch:
    container_name: zammad-elasticsearch
    image: ${IMAGE_REPO}:zammad-elasticsearch${VERSION}
    restart: ${RESTART}
    volumes:
      - ${BUILD_DIR}/zammad/elasticsearch:/usr/share/elasticsearch/data
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.3
        aliases:
          - zammad-elasticsearch
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
          - node.labels.master == true

  zammad-init:
    container_name: zammad-init
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: on-failure
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.4
        aliases:
          - zammad-init
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-memcached:
    container_name: zammad-memcached
    command: ["zammad-memcached"]
    image: ${IMAGE_REPO}:zammad-memcached${VERSION}
    restart: ${RESTART}
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.5
        aliases:
          - zammad-memcached
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-nginx:
    container_name: zammad-nginx
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.6
        aliases:
          - zammad-nginx
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-postgresql:
    container_name: zammad-postgresql
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    restart: ${RESTART}
    volumes:
      - ${DB_DIR}/zammad/postgresql:/var/lib/postgresql/data
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.7
        aliases:
          - zammad-postgresql
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-railsserver:
    container_name: zammad-railsserver
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.8
        aliases:
          - zammad-railserver
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-scheduler:
    container_name: zammad-scheduler
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.9
        aliases:
          - zammad-scheduler
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  zammad-websocket:
    container_name: zammad-websocket
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:zammad${VERSION}
    links:
      - zammad-postgresql
      - zammad-memcached
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.10
        aliases:
          - zammad-websocket
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet

  proxy-zammad:
    container_name: proxy-zammad
    build: ./proxy-zammad
    image: registry.liquibrium.local/proxy-zammad
    container_name: proxy-zammad
    external_links:
      - container-registry
    depends_on:
      - zammad-nginx
    environment:
      VIRTUAL_HOST: helpdesk.liquibrium.com
      LETSENCRYPT_HOST: helpdesk.liquibrium.com
      LETSENCRYPT_EMAIL: admin@liquibrium.com
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.11
        aliases:
          - proxy-zammad
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
          - node.labels.proxy == true

  proxy-zammad-internal:
    container_name: proxy-zammad-internal
    build: ./proxy-zammad
    image: registry.liquibrium.local/proxy-zammad-internal
    container_name: proxy-zammad
    external_links:
      - container-registry
    depends_on:
      - zammad-nginx
    environment:
      VIRTUAL_HOST: helpdesk.liquibrium.local
      NETWORK_ACCESS: internal
    networks:
      operations_intranet:
        ipv4_address: 172.30.88.12
        aliases:
          - proxy-zammad
    deploy:
      placement:
        constraints:
          - node.labels.type == intranet
          - node.labels.proxy == true

networks:
  operations_intranet:
    external: true
