version: '3.4'

services:

  backup:
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    container_name: helpdesk-backup
    command: ["zammad-backup"]
    depends_on:
      - railsserver
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    entrypoint: /usr/local/bin/backup.sh
    links:
      - postgresql
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${DATA_DIR}/zammad/backup:/var/tmp/zammad
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.2
        aliases:
          - zammad-backup
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  elasticsearch:
    image: ${IMAGE_REPO}:zammad-elasticsearch${VERSION}
    container_name: helpdesk-elasticsearch
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${BUILD_DIR}/zammad/elasticsearch:/usr/share/elasticsearch/data:rw
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.3
        aliases:
          - zammad-elasticsearch
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  init:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: helpdesk-init
    command: ["zammad-init"]
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    depends_on:
      - postgresql
    links:
      - elasticsearch
      - postgresql
    restart: on-failure
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.4
        aliases:
          - zammad-init
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  memcached:
    image: memcached:1.6.9-alpine
    container_name: helpdesk-memcached
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    command: memcached -m 256M
    restart: ${RESTART}
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.5
        aliases:
          - zammad-memcached
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  nginx:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: helpdesk-nginx
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    command: ["zammad-nginx"]
    depends_on:
      - railsserver
    links:
      - railsserver
      - websocket
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.6
        aliases:
          - zammad-nginx
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  postgresql:
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    container_name: helpdesk-postgresql
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${DB_DIR}/zammad/postgresql:/var/lib/postgresql/data
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.7
        aliases:
          - zammad-postgresql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  railsserver:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: helpdesk-railsserver
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    command: ["zammad-railsserver"]
    depends_on:
      - memcached
      - postgresql
    links:
      - elasticsearch
      - memcached
      - postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.8
        aliases:
          - zammad-railsserver
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  scheduler:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: helpdesk-scheduler
    command: ["zammad-scheduler"]
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    depends_on:
      - memcached
      - railsserver
    links:
      - elasticsearch
      - memcached
      - postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.9
        aliases:
          - zammad-scheduler
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  websocket:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: helpdesk-websocket
    command: ["zammad-websocket"]
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    depends_on:
      - memcached
      - railsserver
    links:
      - postgresql
      - memcached
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.10
        aliases:
          - zammad-websocket
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  app-proxy:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: helpdesk-app-proxy
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
      - operations-proxy
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://helpdesk-app-proxy"]
      interval: 60s
      timeout: 120s
      start_period: 100s
      retries: 5
    environment:
      VIRTUAL_HOST: helpdesk.finsec.systems
    volumes:
      - ./app-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.11
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  app-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: helpdesk-app-proxy-internal
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
      - operations-proxy
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://helpdesk-app-proxy-internal"]
      interval: 60s
      timeout: 120s
      start_period: 100s
      retries: 5
    environment:
      VIRTUAL_HOST: helpdesk.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./app-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.12
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  pgadmin:
    image: dpage/pgadmin4
    container_name: helpdesk-pgadmin
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
    restart: always
    depends_on:
      - postgresql
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://helpdesk-pgadmin"]
      interval: 60s
      timeout: 120s
      start_period: 100s
      retries: 5
    volumes:
      - ${DATA_DIR}/zammad/pgadmin:/var/lib/pgadmin:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./helpdesk.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.13
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

  pgadmin-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: helpdesk-pgadmin-proxy-internal
    dns: ${DNS_IP_INTERNAL}
    external_links:
      - operations-dns
      - operations-proxy
    depends_on:
      - pgadmin
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-verbose", "--tries=1", "http://helpdesk-pgadmin-proxy-internal"]
      interval: 60s
      timeout: 120s
      start_period: 100s
      retries: 5
    environment:
      VIRTUAL_HOST: helpdeskdb.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./pgadmin-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.14
    logging:
      driver: "fluentd"
      options:
        fluentd-address: logger.finsec.localdomain:24224
        tag: "{{.Name}}.{{.ID}}"
        fluentd-async: "true"

networks:
  operations_intranet:
    external: true
