version: '3.4'

services:

  backup:
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    container_name: zammad-backup
    command: ["zammad-backup"]
    depends_on:
      - railsserver
    entrypoint: /usr/local/bin/backup.sh
    links:
      - postgresql
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${DATA_DIR}/zammad/backup:/var/tmp/zammad
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.2

  elasticsearch:
    image: ${IMAGE_REPO}:zammad-elasticsearch${VERSION}
    container_name: zammad-elasticsearch
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${BUILD_DIR}/zammad/elasticsearch:/usr/share/elasticsearch/data:rw
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.3

  init:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: zammad-init
    command: ["zammad-init"]
    depends_on:
      - postgresql
    links:
      - elasticsearch
      - postgresql
    restart: on-failure
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.4

  memcached:
    image: memcached:1.6.9-alpine
    container_name: zammad-memcached
    command: memcached -m 256M
    restart: ${RESTART}
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.5

  nginx:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: zammad-nginx
    command: ["zammad-nginx"]
    depends_on:
      - railsserver
    links:
      - railsserver
      - websocket
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.6

  postgresql:
    image: ${IMAGE_REPO}:zammad-postgresql${VERSION}
    container_name: zammad-postgresql
    restart: ${RESTART}
    env_file:
      - ./helpdesk.env
    volumes:
      - ${DB_DIR}/zammad/postgresql:/var/lib/postgresql/data
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.7

  railsserver:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: zammad-railsserver
    command: ["zammad-railsserver"]
    depends_on:
      - memcached
      - postgresql
    links:
      - elasticsearch
      - memcached
      - postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.8

  scheduler:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: zammad-scheduler
    command: ["zammad-scheduler"]
    depends_on:
      - memcached
      - railsserver
    links:
      - elasticsearch
      - memcached
      - postgresql
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.9

  websocket:
    image: ${IMAGE_REPO}:zammad${VERSION}
    container_name: zammad-websocket
    command: ["zammad-websocket"]
    depends_on:
      - memcached
      - railsserver
    links:
      - postgresql
      - memcached
    restart: ${RESTART}
    volumes:
      - ${DATA_DIR}/zammad/data:/opt/zammad
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.10

  app-proxy:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: zammad-app-proxy
    depends_on:
      - nginx
    environment:
      VIRTUAL_HOST: helpdesk.finsec.systems
    volumes:
      - ./app-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.11

  app-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: zammad-app-proxy-internal
    depends_on:
      - nginx
    environment:
      VIRTUAL_HOST: helpdesk.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./app-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.12

  pgadmin:
    image: dpage/pgadmin4
    container_name: zammad-pgadmin
    restart: always
    depends_on:
      - postgresql
    volumes:
      - ${DATA_DIR}/zammad/pgadmin:/var/lib/pgadmin:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./helpdesk.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.13

  pgadmin-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: zammad-pgadmin-proxy-internal
    depends_on:
      - pgadmin
    environment:
      VIRTUAL_HOST: helpdeskdb.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./pgadmin-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.12.14

networks:
  operations_intranet:
    external: true
